name: Daily TikTok Post Workflow

on:
  schedule:
    # Runs the content generation script every day at 15:00 UTC.
    # You can change the time. Use a cron calculator like https://crontab.guru/
    - cron: "0 15 * * *"
  workflow_dispatch:
    # This allows you to manually trigger the workflow with a choice.
    inputs:
      action:
        description: 'Choose action to perform'
        required: true
        default: 'publish'
        type: choice
        options:
        - publish
        - regenerate
        - generate_and_publish

jobs:
  generate_content:
    name: "Generate or Regenerate Content"
    permissions:
      contents: write # Grant permission to commit files
    # This job runs on schedule, on 'regenerate', or on 'generate_and_publish'.
    if: >
      github.event_name == 'schedule' ||
      (github.event_name == 'workflow_dispatch' && 
      (github.event.inputs.action == 'regenerate' || github.event.inputs.action == 'generate_and_publish'))
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: "Install dependencies"
        run: pip install -r requirements.txt

      - name: "Run content generation script (files only)"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python generate_content.py --no-slack

      - name: "Commit pending post files"
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add pending_post.json pending_image.png
          if ! git diff --staged --quiet; then
            git commit -m "feat: Add or update pending post"
            git push
          else
            echo "No changes to commit."
          fi
      
      - name: "Send Slack Approval Notification"
        if: success() # Only runs if the commit and push succeeded
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: python generate_content.py --slack-only

  publish_post:
    name: "Publish to TikTok"
    permissions:
      contents: write # Grant permission to delete files
    needs: generate_content
    # This job runs on 'publish', or on 'generate_and_publish' if the generation job succeeded.
    if: >
      always() &&
      (
        (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'publish') ||
        (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'generate_and_publish' && needs.generate_content.result == 'success')
      )
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: "Install dependencies"
        run: pip install -r requirements.txt

      - name: "Run publish script"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          TIKTOK_CLIENT_KEY: ${{ secrets.TIKTOK_CLIENT_KEY }}
          TIKTOK_CLIENT_SECRET: ${{ secrets.TIKTOK_CLIENT_SECRET }}
          TIKTOK_REFRESH_TOKEN: ${{ secrets.TIKTOK_REFRESH_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: python publish_content.py

      - name: "Remove pending post files after publishing"
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git rm pending_post.json pending_image.png
          git commit -m "feat: Clean up published post files"
          git push 